from tkinter import *
from tkinter import messagebox
w=Tk()
w.geometry('3000x2500')
w.title('PERIODIC TABLE')
#functioning of the buttons
def functioning(atmNo,symbol,name,atmMass,state):
    messagebox.showinfo(message=('Atomic number: {} \n Symbol: {} \n Name: {} \n Atomic Mass: {} \n State: {}'.format(atmNo,symbol,name,atmMass,state)))
 
#p=period
p1=Button(w,text='1',highlightcolor='black',font=('Algerian',40),padx=8,pady=10)
p1.grid(row=0,column=0)
p2=Button(w,text='2',highlightcolor='black',font=('Algerian',40),padx=8,pady=10)
p2.grid(row=1,column=0)
p3=Button(w,text='3',highlightcolor='black',font=('Algerian',40),padx=8,pady=10)
p3.grid(row=2,column=0)
p4=Button(w,text='4',highlightcolor='black',font=('Algerian',40),padx=8,pady=10)
p4.grid(row=3,column=0)
p5=Button(w,text='5',highlightcolor='black',font=('Algerian',40),padx=8,pady=10)
p5.grid(row=4,column=0)
p6=Button(w,text='6',highlightcolor='black',font=('Algerian',40),padx=8,pady=10)
p6.grid(row=5,column=0)
p7=Button(w,text='7',highlightcolor='black',font=('Algerian',40),padx=8,pady=10)
p7.grid(row=6,column=0)
#e=elements m=metals (blue) md=metalloids(yellow) n=non metals(green)
#column 1 and 2
emH=Button(text='H',highlightbackground='IndianRed1',font=('Algerian',40),padx=17,pady=10,command=lambda: functioning(atmNo='1',symbol='H',name='Hydrogen',atmMass=1.008,state='Gas')).grid(row=0,column=1)
emLi=Button(text='Li ',highlightbackground='IndianRed1',font=('Algerian',40),padx=12,pady=10,command=lambda: functioning(atmNo='3',symbol='Li',name='Lithium',atmMass=6.941,state='Solid')).grid(row=1,column=1)
emBe=Button(text='Be',highlightbackground='IndianRed1',font=('Algerian',40),padx=8.75,pady=10,command=lambda: functioning(atmNo='4',symbol='Be',name='Berrylium',atmMass=9.012,state='Solid')).grid(row=1,column=2)
emNa=Button(text='Na',highlightbackground='IndianRed1',font=('Algerian',40),padx=7,pady=10,command=lambda: functioning(atmNo='11',symbol='Na',name='Sodium',atmMass=22.990,state='Solid')).grid(row=2,column=1)
emMg=Button(text='Mg',highlightbackground='IndianRed1',font=('Algerian',40),padx=4,pady=10,command=lambda: functioning(atmNo='12',symbol='Mg',name='Magnesium',atmMass=24.305,state='Solid')).grid(row=2,column=2)
emK=Button(text='K',highlightbackground='IndianRed1',font=('Algerian',40),padx=19,pady=10,command=lambda: functioning(atmNo='19',symbol='K',name='Potassium',atmMass=39.098,state='Solid')).grid(row=3,column=1)
emCa=Button(text='Ca',highlightbackground='IndianRed1',font=('Algerian',40),padx=8,pady=10,command=lambda: functioning(atmNo='20',symbol='Ca',name='Calcium',atmMass=40.078,state='Solid')).grid(row=3,column=2)
emRb=Button(text='Rb',highlightbackground='IndianRed1',font=('Algerian',40),padx=8,pady=10,command=lambda: functioning(atmNo='37',symbol='Rb',name='Rubidium',atmMass=84.468,state='Solid')).grid(row=4,column=1)
emSr=Button(text='Sr',highlightbackground='IndianRed1',font=('Algerian',40),padx=14,pady=10,command=lambda: functioning(atmNo='38',symbol='Sr',name='Strontium',atmMass=87.62,state='Solid')).grid(row=4,column=2)
emCs=Button(text='Cs',highlightbackground='IndianRed1',font=('Algerian',40),padx=8,pady=10,command=lambda: functioning(atmNo='55',symbol='Cs',name='Celsium',atmMass=132.905,state='Solid')).grid(row=5,column=1)
emBa=Button(text='Ba',highlightbackground='IndianRed1',font=('Algerian',40),padx=10,pady=10,command=lambda: functioning(atmNo='56',symbol='Ba',name='Barium',atmMass=137.328,state='Solid')).grid(row=5,column=2)
emFr=Button(text='Fr',highlightbackground='IndianRed1',font=('Algerian',40),padx=14,pady=10,command=lambda: functioning(atmNo='87',symbol='Fr',name='Francium',atmMass=223.020,state='Solid')).grid(row=6,column=1)
emRa=Button(text='Ra',highlightbackground='IndianRed1',font=('Algerian',40),padx=10,pady=10,command=lambda: functioning(atmNo='88',symbol='Ra',name='Radium',atmMass=226.025,state='Solid')).grid(row=6,column=2)
#column 3 and 4
emSc=Button(text='Sc',highlightbackground='IndianRed1',font=('Algerian',40),padx=8.5,pady=10,command=lambda: functioning(atmNo='21',symbol='Sc',name='Scandium',atmMass=44.956,state='Solid')).grid(row=3,column=3)
emTi=Button(text='Ti',highlightbackground='IndianRed1',font=('Algerian',40),padx=13,pady=10,command=lambda: functioning(atmNo='22',symbol='Ti',name='Titanium',atmMass=47.88,state='Solid')).grid(row=3,column=4)
emY=Button(text='Y',highlightbackground='IndianRed1',font=('Algerian',40),padx=18.5,pady=10,command=lambda: functioning(atmNo='39',symbol='Y',name='Yttrium',atmMass=88.906,state='Solid')).grid(row=4,column=3)
emZr=Button(text='Zr ',highlightbackground='IndianRed1',font=('Algerian',40),padx=6,pady=10,command=lambda: functioning(atmNo='40',symbol='Zr',name='Zirconium',atmMass=91.224,state='Solid')).grid(row=4,column=4)
emLa=Button(text='La ',highlightbackground='IndianRed1',font=('Algerian',40),padx=6,pady=10,command=lambda: functioning(atmNo='57-71',symbol='La',name='Lanthanides',atmMass=None,state='Solid')).grid(row=5,column=3)
emHf=Button(text='Hf',highlightbackground='IndianRed1',font=('Algerian',40),padx=8.5,pady=10,command=lambda: functioning(atmNo='72',symbol='Hf',name='Berrylium',atmMass=178.49,state='Solid')).grid(row=5,column=4)
emAc=Button(text='Ac',highlightbackground='IndianRed1',font=('Algerian',40),padx=7.5,pady=10,command=lambda: functioning(atmNo='89-103',symbol='Ac',name='Actinisides',atmMass=None,state='Solid')).grid(row=6,column=3)
emRf=Button(text='Rf',highlightbackground='IndianRed1',font=('Algerian',40),padx=11,pady=10,command=lambda: functioning(atmNo='104',symbol='Rf',name='Rutherfordium',atmMass='(261)',state='Solid')).grid(row=6,column=4)
#column 5 and 6 
emV=Button(text='V ',highlightbackground='IndianRed1',font=('Algerian',40),padx=18,pady=10,command=lambda: functioning(atmNo='23',symbol='V',name='Vanadium',atmMass=44.956,state='Solid')).grid(row=3,column=5)
emCr=Button(text='Cr',highlightbackground='IndianRed1',font=('Algerian',40),padx=16,pady=10,command=lambda: functioning(atmNo='24',symbol='Cr',name='Chromium',atmMass=44.956,state='Solid')).grid(row=3,column=6)
emNb=Button(text='Nb',highlightbackground='IndianRed1',font=('Algerian',40),padx=9.5,pady=10,command=lambda: functioning(atmNo='41',symbol='Nb',name='Niobium',atmMass=44.956,state='Solid')).grid(row=4,column=5)
emMo=Button(text=' Mo ',highlightbackground='IndianRed1',font=('Algerian',40),padx=0,pady=10,command=lambda: functioning(atmNo='42',symbol='Mo',name='Molybdenum',atmMass=44.956,state='Solid')).grid(row=4,column=6)
emTa=Button(text='Ta',highlightbackground='IndianRed1',font=('Algerian',40),padx=13,pady=10,command=lambda: functioning(atmNo='73',symbol='Ta',name='Tantalum',atmMass=44.956,state='Solid')).grid(row=5,column=5)
emW=Button(text=' W ',highlightbackground='IndianRed1',font=('Algerian',40),padx=9,pady=10,command=lambda: functioning(atmNo='74',symbol='W',name='Tungsten',atmMass=44.956,state='Solid')).grid(row=5,column=6)
emDb=Button(text='Db',highlightbackground='IndianRed1',font=('Algerian',40),padx=10,pady=10,command=lambda: functioning(atmNo='105',symbol='Db',name='Dubnium',atmMass=44.956,state='Solid')).grid(row=6,column=5)
emSg=Button(text='Sg ',highlightbackground='IndianRed1',font=('Algerian',40),padx=9,pady=10,command=lambda: functioning(atmNo='106',symbol='Sg',name='Seaborgium',atmMass=44.956,state='Solid')).grid(row=6,column=6)
emCe=Button(text='Ce',highlightbackground='IndianRed1',font=('Algerian',40),padx=11,pady=10,command=lambda: functioning(atmNo='58',symbol='Ce',name='Cerium',atmMass=44.956,state='Solid')).grid(row=7,column=5)
emTh=Button(text='Th ',highlightbackground='IndianRed1',font=('Algerian',40),padx=8,pady=10,command=lambda: functioning(atmNo='90',symbol='Th',name='Thorium',atmMass=44.956,state='Solid')).grid(row=8,column=5)
emPr=Button(text='Pr',highlightbackground='IndianRed1',font=('Algerian',40),padx=18,pady=10,command=lambda: functioning(atmNo='59',symbol='Pr',name='Praseodymium',atmMass=44.956,state='Solid')).grid(row=7,column=6)
emPa=Button(text='Pa ',highlightbackground='IndianRed1',font=('Algerian',40),padx=10,pady=10,command=lambda: functioning(atmNo='91',symbol='Pa',name='Protactinium',atmMass=44.956,state='Solid')).grid(row=8,column=6)
#column 7 and 8 
emMn=Button(text=' Mn ',highlightbackground='IndianRed1',font=('Algerian',40),padx=3.25,pady=10,command=lambda: functioning(atmNo='25',symbol='Mn',name='Manganese',atmMass=54.938,state='Solid')).grid(row=3,column=7)
emFe=Button(text='Fe',highlightbackground='IndianRed1',font=('Algerian',40),padx=13,pady=10,command=lambda: functioning(atmNo='26',symbol='Fe',name='Iron',atmMass=55.845,state='Solid')).grid(row=3,column=8)
emTc=Button(text='  Tc  ',highlightbackground='IndianRed1',font=('Algerian',40),padx=0,pady=10,command=lambda: functioning(atmNo='43',symbol='Tc',name='Technetium',atmMass=98.907,state='Solid')).grid(row=4,column=7)
emRu=Button(text=' Ru ',highlightbackground='IndianRed1',font=('Algerian',40),padx=3,pady=10,command=lambda: functioning(atmNo='44',symbol='Ru',name='Ruthenium',atmMass=101.07,state='Solid')).grid(row=4,column=8)
emRe=Button(text=' Re ',highlightbackground='IndianRed1',font=('Algerian',40),padx=8,pady=10,command=lambda: functioning(atmNo='75',symbol='Re',name='Rhenium',atmMass=186.207,state='Solid')).grid(row=5,column=7)
emOs=Button(text='Os',highlightbackground='IndianRed1',font=('Algerian',40),padx=10,pady=10,command=lambda: functioning(atmNo='76',symbol='Os',name='Osmium',atmMass=190.23,state='Solid')).grid(row=5,column=8)
emHs=Button(text=' Bh ',highlightbackground='IndianRed1',font=('Algerian',40),padx=7,pady=10,command=lambda: functioning(atmNo='107',symbol='Bh',name='Bohrium',atmMass='(264)',state='Solid')).grid(row=6,column=7)
emMt=Button(text='Hs',highlightbackground='IndianRed1',font=('Algerian',40),padx=11,pady=10,command=lambda: functioning(atmNo='108',symbol='Hs',name='Hassium',atmMass='(269)',state='Solid')).grid(row=6,column=8)
emNd=Button(text=' Nd  ',highlightbackground='IndianRed1',font=('Algerian',40),padx=1,pady=10,command=lambda: functioning(atmNo='60',symbol='Nd',name='Neodymium',atmMass=144.243,state='Solid')).grid(row=7,column=7)
emU=Button(text='U ',highlightbackground='IndianRed1',font=('Algerian',40),padx=21,pady=10,command=lambda: functioning(atmNo='92',symbol='U',name='Uranium',atmMass=238.029,state='Solid')).grid(row=8,column=7)

emPm=Button(text='Pm ',highlightbackground='IndianRed1',font=('Algerian',40),padx=2,pady=10,command=lambda: functioning(atmNo='61',symbol='Pm',name='Promethium',atmMass=144.913,state='Solid')).grid(row=7,column=8)
emNp=Button(text='Np',highlightbackground='IndianRed1',font=('Algerian',40),padx=9,pady=10,command=lambda: functioning(atmNo='93',symbol='Np',name='Neptunium',atmMass=237.048,state='Solid')).grid(row=8,column=8)
#column 9 and 10
emCo=Button(text=' Co ',highlightbackground='IndianRed1',font=('Algerian',40),padx=3,pady=10,command=lambda: functioning(atmNo='27',symbol='Co',name='Cobalt',atmMass=58.933,state='Solid')).grid(row=3,column=9)
emNi=Button(text='  Ni ',highlightbackground='IndianRed1',font=('Algerian',40),padx=1,pady=10,command=lambda: functioning(atmNo='28',symbol='Ni',name='Nickel',atmMass=58.693,state='Solid')).grid(row=3,column=10)
emRh=Button(text='Rh',highlightbackground='IndianRed1',font=('Algerian',40),padx=13,pady=10,command=lambda: functioning(atmNo='45',symbol='Rh',name='Rhodium',atmMass=102.906,state='Solid')).grid(row=4,column=9)
emPd=Button(text=' Pd',highlightbackground='IndianRed1',font=('Algerian',40),padx=5,pady=10,command=lambda: functioning(atmNo='46',symbol='Pd',name='Palladium',atmMass=106.42,state='Solid')).grid(row=4,column=10)
emIr=Button(text='Ir',highlightbackground='IndianRed1',font=('Algerian',40),padx=25,pady=10,command=lambda: functioning(atmNo='77',symbol='Ir',name='Iridium',atmMass=192.217,state='Solid')).grid(row=5,column=9)
emPt=Button(text='Pt ',highlightbackground='IndianRed1',font=('Algerian',40),padx=10,pady=10,command=lambda: functioning(atmNo='78',symbol='Pt',name='Platinum',atmMass=195.085,state='Solid')).grid(row=5,column=10)
emMt=Button(text='Mt',highlightbackground='IndianRed1',font=('Algerian',40),padx=13,pady=10,command=lambda: functioning(atmNo='109',symbol='Mt',name='Meitnerium',atmMass=(268),state='Solid')).grid(row=6,column=9)
emDs=Button(text='Ds',highlightbackground='IndianRed1',font=('Algerian',40),padx=9,pady=10,command=lambda: functioning(atmNo='110',symbol='Ds',name='Darmstadtium',atmMass=(269),state='Solid')).grid(row=6,column=10)
emSm=Button(text='Sm',highlightbackground='IndianRed1',font=('Algerian',40),padx=8,pady=10,command=lambda: functioning(atmNo='62',symbol='Sm',name='Samarium',atmMass=150.36,state='Solid')).grid(row=7,column=9)
emPu=Button(text='Pu',highlightbackground='IndianRed1',font=('Algerian',40),padx=14,pady=10,command=lambda: functioning(atmNo='94',symbol='Pu',name='Plutonium',atmMass=244.064,state='Solid')).grid(row=8,column=9)

emEu=Button(text='Eu ',highlightbackground='IndianRed1',font=('Algerian',40),padx=6,pady=10,command=lambda: functioning(atmNo='63',symbol='Eu',name='Europium',atmMass=151.964,state='Solid')).grid(row=7,column=10)
emAm=Button(text='Am',highlightbackground='IndianRed1',font=('Algerian',40),padx=3,pady=10,command=lambda: functioning(atmNo='95',symbol='Am',name='Americium',atmMass=243.061,state='Solid')).grid(row=8,column=10)
#column 11 and 12 
emCu=Button(text=' Cu',highlightbackground='IndianRed1',font=('Algerian',40),padx=5,pady=10,command=lambda: functioning(atmNo='29',symbol='Cu',name='Copper',atmMass=63.546,state='Solid')).grid(row=3,column=11)
emZn=Button(text='Zn',highlightbackground='IndianRed1',font=('Algerian',40),padx=15,pady=10,command=lambda: functioning(atmNo='30',symbol='Zn',name='Zinc',atmMass=65.38,state='Solid')).grid(row=3,column=12)
emAg=Button(text=' Ag ',highlightbackground='IndianRed1',font=('Algerian',40),padx=1,pady=10,command=lambda: functioning(atmNo='47',symbol='Ag',name='Silver',atmMass=107.868,state='Solid')).grid(row=4,column=11)
emCd=Button(text='Cd',highlightbackground='IndianRed1',font=('Algerian',40),padx=13,pady=10,command=lambda: functioning(atmNo='48',symbol='Cd',name='Cadmium',atmMass=112.414,state='Solid')).grid(row=4,column=12)
emAu=Button(text='Au',highlightbackground='IndianRed1',font=('Algerian',40),padx=10,pady=10,command=lambda: functioning(atmNo='79',symbol='Au',name='Gold',atmMass=196.967,state='Solid')).grid(row=5,column=11)
emHg=Button(text='Hg',highlightbackground='IndianRed1',font=('Algerian',40),padx=13,pady=10,command=lambda: functioning(atmNo='80',symbol='Hg',name='Mercury',atmMass=200.592,state='Liquid')).grid(row=5,column=12)
emRg=Button(text=' Rg ',highlightbackground='IndianRed1',font=('Algerian',40),padx=2,pady=10,command=lambda: functioning(atmNo='111',symbol='Rg',name='Roentgenium',atmMass='(272',state='Solid')).grid(row=6,column=11)
emCn=Button(text=' Cn ',highlightbackground='IndianRed1',font=('Algerian',40),padx=5,pady=10,command=lambda: functioning(atmNo='112',symbol='Cn',name='Copernicium',atmMass='(277)',state='Solid')).grid(row=6,column=12)
emGd=Button(text='Gd',highlightbackground='IndianRed1',font=('Algerian',40),padx=8,pady=10,command=lambda: functioning(atmNo='64',symbol='Gd',name='Gadolinium',atmMass=157.25,state='Solid')).grid(row=7,column=11)
emCm=Button(text='Cm',highlightbackground='IndianRed1',font=('Algerian',40),padx=3,pady=10,command=lambda: functioning(atmNo='96',symbol='Cm',name='Curium',atmMass=247.070,state='Solid')).grid(row=8,column=11)

emTb=Button(text='Tb',highlightbackground='IndianRed1',font=('Algerian',40),padx=15,pady=10,command=lambda: functioning(atmNo='65',symbol='Tb',name='Terbium',atmMass=158.925,state='Solid')).grid(row=7,column=12)
emBk=Button(text='Bk',highlightbackground='IndianRed1',font=('Algerian',40),padx=16,pady=10,command=lambda: functioning(atmNo='97',symbol='Bk',name='Berkelium',atmMass=247.070,state='Solid')).grid(row=8,column=12)

#column 13 and 14
emdB=Button(text=' B  ',highlightbackground='yellow',font=('Algerian',40),padx=10,pady=10,command=lambda: functioning(atmMass='10.811',symbol='B',name='Boron',atmNo=5,state='Solid')).grid(row=1,column=13)
enC=Button(text='C',highlightbackground='green',font=('Algerian',40),padx=25,pady=10,command=lambda: functioning(atmMass='12.011',symbol='C',name='Carbon',atmNo=6,state='Solid')).grid(row=1,column=14)
emAl=Button(text='Al',highlightbackground='IndianRed1',font=('Algerian',40),padx=18,pady=10,command=lambda: functioning(atmMass='26.982',symbol='Al',name='Aluminium',atmNo=13,state='Solid')).grid(row=2,column=13)
emdSi=Button(text='Si ',highlightbackground='yellow',font=('Algerian',40),padx=18,pady=10,command=lambda: functioning(atmMass='28.086',symbol='Si',name='Silicon',atmNo=14,state='Solid')).grid(row=2,column=14)
emGa=Button(text=' Ga ',highlightbackground='IndianRed1',font=('Algerian',40),padx=2,pady=10,command=lambda: functioning(atmMass='69.723',symbol='Ga',name='Gallium',atmNo=31,state='Solid')).grid(row=3,column=13)
emdGe=Button(text='Ge',highlightbackground='yellow',font=('Algerian',40),padx=14,pady=10,command=lambda: functioning(atmMass='72.631',symbol='Ge',name='Germanium',atmNo=32,state='Solid')).grid(row=3,column=14)
emIn=Button(text='In',highlightbackground='IndianRed1',font=('Algerian',40),padx=20,pady=10,command=lambda: functioning(atmMass='114.818',symbol='In',name='Indium',atmNo=49,state='Solid')).grid(row=4,column=13)
emSn=Button(text='Sn',highlightbackground='IndianRed1',font=('Algerian',40),padx=16,pady=10,command=lambda: functioning(atmMass='118.711',symbol='Sn',name='Tin',atmNo=50,state='Solid')).grid(row=4,column=14)
emTl=Button(text='Tl',highlightbackground='IndianRed1',font=('Algerian',40),padx=19,pady=10,command=lambda: functioning(atmMass='204.383',symbol='Tl',name='Thallium',atmNo=81,state='Solid')).grid(row=5,column=13)
emPb=Button(text=' Pb  ',highlightbackground='IndianRed1',font=('Algerian',40),padx=3,pady=10,command=lambda: functioning(atmMass='207.2',symbol='Pb',name='Lead',atmNo=82,state='Solid')).grid(row=5,column=14)
emUnt=Button(text='Uut',highlightbackground='IndianRed1',font=('Algerian',40),padx=4,pady=10,command=lambda: functioning(atmMass='~unknown~',symbol='Uut',name='Ununtrium',atmNo=113,state='Solid')).grid(row=6,column=13)
emUuq=Button(text='Fl',highlightbackground='IndianRed1',font=('Algerian',40),padx=23,pady=10,command=lambda: functioning(atmMass='(289)',symbol='Fl',name='Flerovium',atmNo=114,state='Solid')).grid(row=6,column=14)

emDy=Button(text='Dy',highlightbackground='IndianRed1',font=('Algerian',40),padx=11,pady=10,command=lambda: functioning(atmNo='66',symbol='Dy',name='Dysprosium',atmMass=162.500,state='Solid')).grid(row=7,column=13)
emCf=Button(text='Cf',highlightbackground='IndianRed1',font=('Algerian',40),padx=15,pady=10,command=lambda: functioning(atmNo='98',symbol='Cf',name='Californium',atmMass=251.080,state='Solid')).grid(row=8,column=13)

emHo=Button(text='Ho',highlightbackground='IndianRed1',font=('Algerian',40),padx=14,pady=10,command=lambda: functioning(atmNo='67',symbol='Ho',name='Holmium',atmMass=164.930,state='Solid')).grid(row=7,column=14)
emEs=Button(text='Es',highlightbackground='IndianRed1',font=('Algerian',40),padx=18,pady=10,command=lambda: functioning(atmNo='99',symbol='Es',name='Einsteinium',atmMass='(254)',state='Solid')).grid(row=8,column=14)

#column 15 and 16
enN=Button(text='N',highlightbackground='green',font=('Algerian',40),padx=24,pady=10,command=lambda: functioning(atmNo='7',symbol='N',name='Nitrogen',atmMass=14.007,state='Gas')).grid(row=1,column=15)
enO=Button(text='O',highlightbackground='green',font=('Algerian',40),padx=25,pady=10,command=lambda: functioning(atmNo='8',symbol='O',name='Oxygen',atmMass=15.999,state='Gas')).grid(row=1,column=16)
enP=Button(text=' P ',highlightbackground='green',font=('Algerian',40),padx=18,pady=10,command=lambda: functioning(atmNo='15',symbol='P',name='Phosphorus',atmMass=30.974,state='Solid')).grid(row=2,column=15)
enS=Button(text=' S ',highlightbackground='green',font=('Algerian',40),padx=19,pady=10,command=lambda: functioning(atmNo='16',symbol='S',name='Sulphur',atmMass=32.066,state='Solid')).grid(row=2,column=16)
emdAs=Button(text='As',highlightbackground='yellow',font=('Algerian',40),padx=16,pady=10,command=lambda: functioning(atmNo='33',symbol='As',name='Arsenic',atmMass=74.922,state='Solid')).grid(row=3,column=15)
enSe=Button(text='  Se  ',highlightbackground='green',font=('Algerian',40),padx=0,pady=10,command=lambda: functioning(atmNo='34',symbol='Se',name='Selenium',atmMass=78.971,state='Solid')).grid(row=3,column=16)
emdSb=Button(text='Sb',highlightbackground='yellow',font=('Algerian',40),padx=15,pady=10,command=lambda: functioning(atmNo='51',symbol='Sb',name='Antimony',atmMass=121.760,state='Solid')).grid(row=4,column=15)
emdTe=Button(text=' Te ',highlightbackground='yellow',font=('Algerian',40),padx=9,pady=10,command=lambda: functioning(atmNo='52',symbol='Te',name='Tellurium',atmMass=127.6,state='Solid')).grid(row=4,column=16)
emBi=Button(text=' Bi ',highlightbackground='IndianRed1',font=('Algerian',40),padx=13,pady=10,command=lambda: functioning(atmNo='83',symbol='Bi',name='Bismuth',atmMass=208.960,state='Solid')).grid(row=5,column=15)
emdPo=Button(text='Po',highlightbackground='yellow',font=('Algerian',40),padx=17,pady=10,command=lambda: functioning(atmNo='84',symbol='Po',name='Polonium',atmMass='(208.982)',state='Solid')).grid(row=5,column=16)
emUnp=Button(text='Uup',highlightbackground='IndianRed1',font=('Algerian',40),padx=2,pady=10,command=lambda: functioning(atmNo='115',symbol='Uup',name='Ununpentium',atmMass='~unknown~',state='Solid')).grid(row=6,column=15)
emUuh=Button(text='Lv',highlightbackground='IndianRed1',font=('Algerian',40),padx=18,pady=10,command=lambda: functioning(atmNo='116',symbol='Lv',name='Livermorium',atmMass='(298)',state='Solid')).grid(row=6,column=16)
emEr=Button(text='Er',highlightbackground='IndianRed1',font=('Algerian',40),padx=20,pady=10,command=lambda: functioning(atmNo='68',symbol='Er',name='Erbium',atmMass=167.259,state='Solid')).grid(row=7,column=15)
emFm=Button(text='Fm',highlightbackground='IndianRed1',font=('Algerian',40),padx=11,pady=10,command=lambda: functioning(atmNo='100',symbol='Fm',name='Fermium',atmMass=257.095,state='Solid')).grid(row=8,column=15)

emTm=Button(text=' Tm ',highlightbackground='IndianRed1',font=('Algerian',40),padx=3,pady=10,command=lambda: functioning(atmNo='69',symbol='Tm',name='Thullium',atmMass=168.934,state='Solid')).grid(row=7,column=16)
emMd=Button(text=' Md ',highlightbackground='IndianRed1',font=('Algerian',40),padx=3,pady=10,command=lambda: functioning(atmNo='101',symbol='Md',name='Mendelevium',atmMass=258.1,state='Solid')).grid(row=8,column=16)

#column 17 and 18
enHe=Button(text='He',highlightbackground='green',font=('Algerian',40),padx=16,pady=10,command=lambda: functioning(atmNo='2',symbol='He',name='Helium',atmMass=4.003,state='Gas')).grid(row=0,column=18)
enF=Button(text='F ',highlightbackground='green',font=('Algerian',40),padx=23,pady=10,command=lambda: functioning(atmNo='9',symbol='F',name='Fluroine',atmMass=18.998,state='Gas')).grid(row=1,column=17)
enNe=Button(text='Ne',highlightbackground='green',font=('Algerian',40),padx=16,pady=10,command=lambda: functioning(atmNo='10',symbol='Ne',name='Neon',atmMass=20.180,state='Gas')).grid(row=1,column=18)
enCl=Button(text='Cl',highlightbackground='green',font=('Algerian',40),padx=20,pady=10,command=lambda: functioning(atmNo='17',symbol='Cl',name='Chlorine',atmMass=35.453,state='Gas')).grid(row=2,column=17)
enAr=Button(text='Ar',highlightbackground='green',font=('Algerian',40),padx=22,pady=10,command=lambda: functioning(atmNo='18',symbol='Ar',name='Argon',atmMass=39.948,state='Gas')).grid(row=2,column=18)
enBr=Button(text=' Br ',highlightbackground='green',font=('Algerian',40),padx=11,pady=10,command=lambda: functioning(atmNo='35',symbol='Br',name='Bromine',atmMass=79.904,state='Liquid')).grid(row=3,column=17)
enKr=Button(text='Kr',highlightbackground='green',font=('Algerian',40),padx=22,pady=10,command=lambda: functioning(atmNo='36',symbol='Kr',name='Krypton',atmMass=84.798,state='Gas')).grid(row=3,column=18)
enI=Button(text=' I ',highlightbackground='green',font=('Algerian',40),padx=25,pady=10,command=lambda: functioning(atmNo='53',symbol='I',name='Iodine',atmMass=126.904,state='Solid')).grid(row=4,column=17)
enXe=Button(text='Xe',highlightbackground='green',font=('Algerian',40),padx=18,pady=10,command=lambda: functioning(atmNo='54',symbol='Xe',name='Xenon',atmMass=131.249,state='Gas')).grid(row=4,column=18)
emdAt=Button(text='At',highlightbackground='yellow',font=('Algerian',40),padx=19,pady=10,command=lambda: functioning(atmNo='85',symbol='At',name='Astatine',atmMass=209.987,state='Solid')).grid(row=5,column=17)
enRn=Button(text='Rn',highlightbackground='green',font=('Algerian',40),padx=18,pady=10,command=lambda: functioning(atmNo='86',symbol='Rn',name='Radon',atmMass=222.018,state='Gas')).grid(row=5,column=18)
emUns=Button(text='Uus',highlightbackground='IndianRed1',font=('Algerian',40),padx=4,pady=10,command=lambda: functioning(atmNo='117',symbol='Uus',name='Ununseptium',atmMass='~unknown~',state='Solid')).grid(row=6,column=17)
emUno=Button(text='Uuo',highlightbackground='IndianRed1',font=('Algerian',40),padx=5,pady=10,command=lambda: functioning(atmNo='118',symbol='Uuo',name='Ununoctium',atmMass='~unknown~',state='Solid')).grid(row=6,column=18)

emYb=Button(text='Yb',highlightbackground='IndianRed1',font=('Algerian',40),padx=14,pady=10,command=lambda: functioning(atmNo='70',symbol='Yb',name='Ytterbium',atmMass=173.055,state='Solid')).grid(row=7,column=17)
emNo=Button(text='No',highlightbackground='IndianRed1',font=('Algerian',40),padx=13,pady=10,command=lambda: functioning(atmNo='102',symbol='No',name='Nobelium',atmMass=259.101,state='Solid')).grid(row=8,column=17)

emLu=Button(text='Lu',highlightbackground='IndianRed1',font=('Algerian',40),padx=20,pady=10,command=lambda: functioning(atmNo='71',symbol='Lu',name='Lutetium',atmMass=174.967,state='Solid')).grid(row=7,column=18)
emLr=Button(text='Lr',highlightbackground='IndianRed1',font=('Algerian',40),padx=24,pady=10,command=lambda: functioning(atmNo='103',symbol='Lr',name='Lawrencium',atmMass='(262)',state='Solid')).grid(row=8,column=18)

#special buttons
Special=Label(w,text='Sort elements on the basis of:-',font=('Comic Sans MS',45),highlightcolor='black',highlightthickness='5').grid(row=9,column=0,columnspan=30)
sbMetals=Button(w,text='METALS',highlightbackground='IndianRed1',font=('Algerian',35),padx=20,pady=10).grid(row=10,column=0,columnspan=10)
sbMetalloids=Button(w,text='METALLOIDS',highlightbackground='yellow',font=('Algerian',35),padx=20,pady=10).grid(row=10,column=4,columnspan=10)
sbNonmetals=Button(w,text='NON-METALS',highlightbackground='green',font=('Algerian',35),padx=20,pady=10).grid(row=10,column=8,columnspan=10)
#abAll=Button(w,text='ALL',highlightbackground='SteelBlue1',font=('Algerian',35),padx=20,pady=10).grid(row=10,column=13,columnspan=10)
w.mainloop()
